# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)

development: &default
  adapter: mysql2
  user: root
  database: allourideas_development
  pool: 5
  host: aoi_db
  port: 3306
  username: root
  password: 123456
  timeout: 5000

production:
  adapter: <%= ENV['RAILS_DB_ADAPTER'] || 'mysql2' %>
  host: <%= ENV['RAILS_DB_HOST'] || 'aoi-db' %>
  port: <%= ENV['RAILS_DB_PORT'] || 3306 %>
  user: <%= ENV['RAILS_DB_USERNAME'] || 'root' %>
  username: <%= ENV['RAILS_DB_USERNAME'] || 'root' %>
  password: <%= ENV['RAILS_DB_PASSWORD'] || '123456' %>
  database: <%= ENV['RAILS_DB_NAME'] || 'allourideas_production' %>
  pool: 5
  timeout: 5000

#development: &default
#  adapter: sqlite3
#  database: db/development.sqlite3
#  pool: 5
#  timeout: 5000

test: &TEST
  adapter: sqlite3
  database: db/test.sqlite3

staging:
  <<: *default


cucumber:
  <<: *TEST
